INSERT INTO alimentos(descricao, "createdAt", "updatedAt")
VALUES
('Abacate', now(), now() ),
('Abacaxi', now(), now() ),
('Abiu', now(), now() ),
('Abóbora', now(), now() ),
('Abóbora cozida', now(), now() ),
('Abóbora refogada', now(), now() ),
('Abobrinha', now(), now() ),
('Açaí', now(), now() ),
('Açaí (sem açúcar e sem farinha) ', now(), now() ),
('Açaí com açúcar ', now(), now() ),
('Açaí com farinha de mandioca ', now(), now() ),
('Açaí com farinha de tapioca ', now(), now() ),
('Açaí com farinha e açúcar ', now(), now() ),
('Acerola', now(), now() ),
('Achocolatado Nescau(R) light', now(), now() ),
('Achocolatado pó', now(), now() ),
('Açúcar', now(), now() ),
('Açúcar mascavo', now(), now() ),
('Açúcar refinado', now(), now() ),
('Ades(R) original', now(), now() ),
('Água de coco', now(), now() ),
('Água de laranjeira', now(), now() ),
('Aguardente', now(), now() ),
('Aipim cozido', now(), now() ),
('Aipim frito', now(), now() ),
('Aipo verde pó', now(), now() ),
('Alcaparra', now(), now() ),
('Alecrim fresco', now(), now() ),
('Alface', now(), now() ),
('Alfavaca', now(), now() ),
('Alho desidratado', now(), now() ),
('Alho fresco', now(), now() ),
('Alho poró', now(), now() ),
('Amendoim', now(), now() ),
('Amendoim japonês', now(), now() ),
('Amendoim torrado com sal', now(), now() ),
('Amido de milho ', now(), now() ),
('Ananás ', now(), now() ),
('Angélica desidratada', now(), now() ),
('Angu', now(), now() ),
('Anis em pó', now(), now() ),
('Anis estrelado', now(), now() ),
('Apresuntado', now(), now() ),
('Apresuntado Sadia (R)', now(), now() ),
('Araçá ', now(), now() ),
('Arroz', now(), now() ),
('Arroz branco cozido', now(), now() ),
('Arroz com leite', now(), now() ),
('Arroz cozido', now(), now() ),
('Arroz doce ', now(), now() ),
('Arroz integral com sal ', now(), now() ),
('Arroz integral cozido', now(), now() ),
('Arroz japonês', now(), now() ),
('Arroz Maria Isabel', now(), now() ),
('Arruda fresca', now(), now() ),
('Artemísia', now(), now() ),
('Ata (Fruta do conde)', now(), now() ),
('Atum', now(), now() ),
('Atum sólido em água e sal Coqueiro (R)', now(), now() ),
('Atum sólido em óleo Coqueiro (R) ', now(), now() ),
('Aveia em flocos', now(), now() ),
('Azeite de dendê', now(), now() ),
('Azeite de oliva', now(), now() ),
('Azeitona sem caroço', now(), now() ),
('Azeitona verde', now(), now() ),
('Bacaba ', now(), now() ),
('Bacalhau cozido', now(), now() ),
('Bacon', now(), now() ),
('Bacuri ', now(), now() ),
('Baião de dois', now(), now() ),
('Banana da terra', now(), now() ),
('Banana maçã', now(), now() ),
('Banana ouro', now(), now() ),
('Banana passa', now(), now() ),
('Banana prata', now(), now() ),
('Banana-nanica', now(), now() ),
('Bananada', now(), now() ),
('Banha de porco', now(), now() ),
('Batata palha', now(), now() ),
('Batata-doce', now(), now() ),
('Batata-doce cozida', now(), now() ),
('Batata-doce frita', now(), now() ),
('Batata-inglesa', now(), now() ),
('Batata-inglesa cozida', now(), now() ),
('Batata-inglesa frita', now(), now() ),
('Batida (similar à rapadura)', now(), now() ),
('Beiju ', now(), now() ),
('Beiju com coco ', now(), now() ),
('Berinjela', now(), now() ),
('Beterraba cozida', now(), now() ),
('Beterraba crua ralada', now(), now() ),
('Bicarbonato de sódio', now(), now() ),
('Bife bovino', now(), now() ),
('Bife bovino à milanesa', now(), now() ),
('Bife de fígado bovino', now(), now() ),
('Biscoito água', now(), now() ),
('Biscoito Club Social (R) ', now(), now() ),
('Biscoito Club Social (R) Nabisco', now(), now() ),
('Biscoito Cream Cracker', now(), now() ),
('Biscoito Doritos (R) original', now(), now() ),
('Biscoito Fandangos (R) Queijo', now(), now() ),
('Biscoito Fofitos (R) Fortaleza', now(), now() ),
('Biscoito folheado', now(), now() ),
('Biscoito Maizena (R) ', now(), now() ),
('Biscoito Maria', now(), now() ),
('Biscoito Passatempo (R) recheado', now(), now() ),
('Biscoito Polvilho', now(), now() ),
('Biscoito recheado', now(), now() ),
('Bolacha Romita (R) Romana', now(), now() ),
('Bolinho de bacalhau', now(), now() ),
('Bolo', now(), now() ),
('Bolo branco simples', now(), now() ),
('Bolo de cenoura', now(), now() ),
('Bolo de farinha de tapioca ', now(), now() ),
('Bolo de macaxeira ', now(), now() ),
('Bolo de milho', now(), now() ),
('Bombom (bala)', now(), now() ),
('Brigadeiro', now(), now() ),
('Bruaca', now(), now() ),
('Bulin de goma (polvilho)', now(), now() ),
('Buriti ', now(), now() ),
('Cachorro-quente', now(), now() ),
('Café com leite com açúcar', now(), now() ),
('Café com leite sem açúcar', now(), now() ),
('Café em pó solúvel', now(), now() ),
('Café infusão com açúcar', now(), now() ),
('Cajá', now(), now() ),
('Caju', now(), now() ),
('Caldeirada paraense ', now(), now() ),
('Caldo de carne', now(), now() ),
('Caldo de feijão', now(), now() ),
('Caldo de frango', now(), now() ),
('Caldo de galinha', now(), now() ),
('Caldo de legumes', now(), now() ),
('Caldo de peixe', now(), now() ),
('Caldo verde', now(), now() ),
('Caldo-de-cana ', now(), now() ),
('Camarão', now(), now() ),
('Camarão ao Catupiry (R) ', now(), now() ),
('Camarão empanado', now(), now() ),
('Camu-camu ', now(), now() ),
('Canela em pó', now(), now() ),
('Canela rama', now(), now() ),
('Canja', now(), now() ),
('Canjica', now(), now() ),
('Canjica de milho verde', now(), now() ),
('Cappuccino em pó', now(), now() ),
('Cará cozido ', now(), now() ),
('Caranguejo (carne)', now(), now() ),
('Cardamomo em pó', now(), now() ),
('Cardamomo semente', now(), now() ),
('Carne bovina', now(), now() ),
('Carne bovina assada', now(), now() ),
('Carne bovina ensopada', now(), now() ),
('Carne bovina moída', now(), now() ),
('Carne de baby búfalo ', now(), now() ),
('Carne de carneiro', now(), now() ),
('Carne desfiada', now(), now() ),
('Carne em lata', now(), now() ),
('Carne moída', now(), now() ),
('Carne moída com legumes', now(), now() ),
('Carne moída com purê (Madalena)', now(), now() ),
('Carne no churrasco', now(), now() ),
('Carne seca', now(), now() ),
('Caruru paraense ', now(), now() ),
('Casca de laranja', now(), now() ),
('Casquinha de sorvete', now(), now() ),
('Casquinho de caranguejo ', now(), now() ),
('Castanha de caju', now(), now() ),
('Castanha de caju torrada', now(), now() ),
('Castanha do Pará', now(), now() ),
('Castanha-do- pará ', now(), now() ),
('Catchup', now(), now() ),
('Cebola', now(), now() ),
('Cebola desidratada', now(), now() ),
('Cebolinha fresca', now(), now() ),
('Cenoura cozida', now(), now() ),
('Cenoura crua', now(), now() ),
('Cenoura crua ralada', now(), now() ),
('Cenoura refogada', now(), now() ),
('Cereal matinal Corn Flakes (R) Kellogs', now(), now() ),
('Cereal matinal Sucrilho (R) ', now(), now() ),
('Cerveja', now(), now() ),
('Cheeseburguer', now(), now() ),
('Chiclete', now(), now() ),
('Chikuwa', now(), now() ),
('Chilli', now(), now() ),
('Chimi churri', now(), now() ),
('Chocolate', now(), now() ),
('Chocolate barra Chokito (R) Nestlé', now(), now() ),
('Chocolate barra Diamante Negro (R) Lacta', now(), now() ),
('Chocolate barra Galak (R) Nestlé', now(), now() ),
('Chocolate Nucita (R) ', now(), now() ),
('Chuchu à milanesa', now(), now() ),
('Chuchu cozido', now(), now() ),
('Chuchu refogado', now(), now() ),
('Churrasco', now(), now() ),
('Coalhada', now(), now() ),
('Cocada', now(), now() ),
('Coco seco', now(), now() ),
('Coco verde ', now(), now() ),
('Coentro desidratado', now(), now() ),
('Coentro em pó', now(), now() ),
('Cominho grão', now(), now() ),
('Coração de galinha cozido', now(), now() ),
('Costela de porco cozida', now(), now() ),
('Couve crua', now(), now() ),
('Couve refogada', now(), now() ),
('Couve-flor', now(), now() ),
('Cozidão (só a carne) ', now(), now() ),
('Cravo da índia', now(), now() ),
('Creme de cebola em pó', now(), now() ),
('Creme de chocolate', now(), now() ),
('Creme de galinha', now(), now() ),
('Creme de leite', now(), now() ),
('Cupuaçu (polpa) ', now(), now() ),
('Cúrcuma', now(), now() ),
('Curry', now(), now() ),
('Cuscuz de milho', now(), now() ),
('Cuscuz de milho com leite', now(), now() ),
('Doce de banana', now(), now() ),
('Doce de leite', now(), now() ),
('Doce de leite cremoso', now(), now() ),
('Docinho de festa', now(), now() ),
('Empada de frango', now(), now() ),
('Endro em grãos', now(), now() ),
('Endro fresco', now(), now() ),
('Erva doce fresca', now(), now() ),
('Ervilha em lata', now(), now() ),
('Esfiha de carne', now(), now() ),
('Espinafre cozido', now(), now() ),
('Estragão desidratado', now(), now() ),
('Farinha de mandioca', now(), now() ),
('Farinha de mandioca ', now(), now() ),
('Farinha de tapioca ', now(), now() ),
('Farinha láctea', now(), now() ),
('Farofa', now(), now() ),
('Farofa ', now(), now() ),
('Farofa com linguiça', now(), now() ),
('Farofa de lingüiça', now(), now() ),
('Farofa de ovo', now(), now() ),
('Farofa de sardinha', now(), now() ),
('Farofa de soja', now(), now() ),
('Feijão', now(), now() ),
('Feijão branco cozido', now(), now() ),
('Feijão com legumes', now(), now() ),
('Feijão preto cozido', now(), now() ),
('Feijoada caseira', now(), now() ),
('Fenogrego grão', now(), now() ),
('Fermento em pó químico', now(), now() ),
('Fígado', now(), now() ),
('Filé trinchado', now(), now() ),
('Finas ervas desidratadas', now(), now() ),
('Frango', now(), now() ),
('Frango à milanesa', now(), now() ),
('Frango assado', now(), now() ),
('Frango desfiado', now(), now() ),
('Frango ensopado', now(), now() ),
('Frango frito', now(), now() ),
('Fruta seca', now(), now() ),
('Fubá', now(), now() ),
('Garam masala', now(), now() ),
('Gelatina', now(), now() ),
('Gelatina Jellys (R) ', now(), now() ),
('Gelatina preparada', now(), now() ),
('Geleia', now(), now() ),
('Geleia de mocotó', now(), now() ),
('Gengibre fresco', now(), now() ),
('Gergelim', now(), now() ),
('Goiaba', now(), now() ),
('Goiabada', now(), now() ),
('Granola', now(), now() ),
('Grão de bico cozido', now(), now() ),
('Graviola', now(), now() ),
('Hamburquer', now(), now() ),
('Hortelá in natura', now(), now() ),
('Ingá ', now(), now() ),
('Iogurte', now(), now() ),
('Iogurte desnatado', now(), now() ),
('Iogurte natural', now(), now() ),
('Jambo ', now(), now() ),
('Jambu ', now(), now() ),
('Kalzone frango catupiry (R) ', now(), now() ),
('Kalzone integral de brócolis com ricota e cenoura (R) ', now(), now() ),
('Kare-raisu', now(), now() ),
('Ketchup', now(), now() ),
('Konnyaku', now(), now() ),
('Kummel (alcarávia)', now(), now() ),
('Laranja', now(), now() ),
('Lasanha à bolonhesa', now(), now() ),
('Leite com abacate', now(), now() ),
('Leite com banana', now(), now() ),
('Leite condensado', now(), now() ),
('Leite de soja', now(), now() ),
('Leite de vaca desnatado', now(), now() ),
('Leite de vaca integral', now(), now() ),
('Leite em pó', now(), now() ),
('Leite Moça Fiesta (R) ', now(), now() ),
('Lentilha cozida', now(), now() ),
('Limão', now(), now() ),
('Linguiça', now(), now() ),
('Lingüiça calabresa', now(), now() ),
('Lingüiça toscana', now(), now() ),
('Linhaça', now(), now() ),
('Louro desidratado', now(), now() ),
('Louro em pó', now(), now() ),
('Maçã', now(), now() ),
('Macarrão', now(), now() ),
('Macarrão ao alho e óleo', now(), now() ),
('Macarrão Nissin Miojo (R) ', now(), now() ),
('Macarronada', now(), now() ),
('Macaxeira cozida', now(), now() ),
('Macaxeira cozida ', now(), now() ),
('Macaxeira frita', now(), now() ),
('Macaxeira frita ', now(), now() ),
('Maionese industrializada', now(), now() ),
('Mamão', now(), now() ),
('Mamão papaya', now(), now() ),
('Manga', now(), now() ),
('Maniçoba ', now(), now() ),
('Manjericão desidratado', now(), now() ),
('Manjerona desidratada', now(), now() ),
('Manjerona in natura', now(), now() ),
('Manteiga', now(), now() ),
('Manteiga com sal', now(), now() ),
('Mão de vaca', now(), now() ),
('Margarina', now(), now() ),
('Maxixe', now(), now() ),
('Melancia', now(), now() ),
('Melão', now(), now() ),
('Melissa desidratada', now(), now() ),
('Menta fresca', now(), now() ),
('Milho', now(), now() ),
('Milho verde (espiga) ', now(), now() ),
('Milho-verde', now(), now() ),
('Minipizza', now(), now() ),
('Miso', now(), now() ),
('Misoshiro', now(), now() ),
('Misto quente', now(), now() ),
('Moela de galinha', now(), now() ),
('Molho inglês', now(), now() ),
('Morango', now(), now() ),
('Mortadela', now(), now() ),
('Mostarda', now(), now() ),
('Mostarda amarela grão', now(), now() ),
('Mostarda condimento', now(), now() ),
('Mousse de maracujá', now(), now() ),
('Mungunzá doce', now(), now() ),
('Murici', now(), now() ),
('Natto', now(), now() ),
('Nishime', now(), now() ),
('Noz moscada em pó', now(), now() ),
('Óleo de coco', now(), now() ),
('Óleo vegetal', now(), now() ),
('Omelete', now(), now() ),
('Óregano chileno', now(), now() ),
('Ossobuco', now(), now() ),
('Ovo de codorna', now(), now() ),
('Ovo de galinha clara cozida', now(), now() ),
('Ovo de galinha cozido', now(), now() ),
('Ovo de galinha frito', now(), now() ),
('Ovo de Páscoa', now(), now() ),
('Paçoca de carne de sol', now(), now() ),
('Pamonha', now(), now() ),
('Panelada', now(), now() ),
('Pão amor', now(), now() ),
('Pão árabe', now(), now() ),
('Pão de coco', now(), now() ),
('Pão de forma branco', now(), now() ),
('Pão de hamburguer', now(), now() ),
('Pão de queijo', now(), now() ),
('Pão francês', now(), now() ),
('Pão hot dog', now(), now() ),
('Páprica doce', now(), now() ),
('Páprica picante', now(), now() ),
('Pastel', now(), now() ),
('Pato no tucupi (pato, arroz, tucupi, jambu e farinha)', now(), now() ),
('Peixe à milanesa', now(), now() ),
('Peixe cará ou tilápia ou Saint Peter', now(), now() ),
('Peixe cozido', now(), now() ),
('Peixe ensopado', now(), now() ),
('Peixe frito', now(), now() ),
('Peixe pargo', now(), now() ),
('Peixe piaba', now(), now() ),
('Pepino', now(), now() ),
('Picolé Chicabon (R) Kibon', now(), now() ),
('Picolé coco ao leite (R) Kibon', now(), now() ),
('Picolé Magnum branco (R) Kibon', now(), now() ),
('Pimenta caiena', now(), now() ),
('Pimenta calabresa', now(), now() ),
('Pimenta da Jamaica', now(), now() ),
('Pimenta do reino', now(), now() ),
('Pimenta doce', now(), now() ),
('Pimentão', now(), now() ),
('Pipoca', now(), now() ),
('Pipoca com sal', now(), now() ),
('Pipoca de "isopor"', now(), now() ),
('Piquiá', now(), now() ),
('Pirão de farinha de mandioca ', now(), now() ),
('Pirarucu (frito)', now(), now() ),
('Pirulito', now(), now() ),
('Pitomba', now(), now() ),
('Pizza calabresa', now(), now() ),
('Pizza muçarela', now(), now() ),
('Polpa de fruta', now(), now() ),
('Presunto', now(), now() ),
('Presunto com capa de gordura Sadia (R) ', now(), now() ),
('Presunto sem capa de gordura Sadia (R) ', now(), now() ),
('Pudim', now(), now() ),
('Pupunha ', now(), now() ),
('Quebra-queixo (doce com coco)', now(), now() ),
('Queijo coalho', now(), now() ),
('Queijo gorgonzola', now(), now() ),
('Queijo muçarela', now(), now() ),
('Queijo prato', now(), now() ),
('Queijo prato light', now(), now() ),
('Queijo quente (sanduíche)', now(), now() ),
('Quiabo', now(), now() ),
('Rabada', now(), now() ),
('Raiz forte', now(), now() ),
('Refrigerante', now(), now() ),
('Refrigerante cola', now(), now() ),
('Refrigerante cola light', now(), now() ),
('Repolho cru', now(), now() ),
('Requeijão', now(), now() ),
('Sal grosso', now(), now() ),
('Sal refinado', now(), now() ),
('Salada cozida', now(), now() ),
('Salada crua', now(), now() ),
('Salada de abacaxi, beterraba, cenoura, manga e passas', now(), now() ),
('Salada de abobrinha, batata palha e presunto', now(), now() ),
('Salada de acelga, alface, beterraba e cenoura', now(), now() ),
('Salada de acelga, cenoura e repolho', now(), now() ),
('Salada de alface e tomate', now(), now() ),
('Salada de alface, abacaxi e passas', now(), now() ),
('Salada de alface, abacaxi, repolho e tomate', now(), now() ),
('Salada de alface, batata e cenoura com maionese', now(), now() ),
('Salada de alface, batata palha e tomate', now(), now() ),
('Salada de alface, cebola, cenoura, passas, repolho e tomate', now(), now() ),
('Salada de alface, manga e tomate', now(), now() ),
('Salada de ameixa, beterraba e cenoura', now(), now() ),
('Salada de azeitona, cenoura, milho verde, passas e vagem', now(), now() ),
('Salada de batata com maionese', now(), now() ),
('Salada de beterraba e cenoura cozidas', now(), now() ),
('Salada de beterraba e cenoura cruas', now(), now() ),
('Salada de cenoura, repolho e tomate', now(), now() ),
('Salada de frutas', now(), now() ),
('Salada de legumes (batata, cenoura, chuchu)', now(), now() ),
('Salgadinho de aniversário', now(), now() ),
('Salgado de lanche', now(), now() ),
('Salsa fresca', now(), now() ),
('Salsicha', now(), now() ),
('Salsicha com molho', now(), now() ),
('Salsicha de frango', now(), now() ),
('Salsicha hot dog', now(), now() ),
('Sálvia desidratada', now(), now() ),
('Sálvia fresca', now(), now() ),
('Sapoti', now(), now() ),
('Sardinha', now(), now() ),
('Sardinha com ovos', now(), now() ),
('Sardinha em conserva', now(), now() ),
('Sashimi', now(), now() ),
('Segurelha desidratada', now(), now() ),
('Sementes de papoula', now(), now() ),
('Seriguela', now(), now() ),
('Shiruko', now(), now() ),
('Shoyo', now(), now() ),
('Soja (grão)', now(), now() ),
('Soja (proteína texturizada)', now(), now() ),
('Sopa carne e legumes', now(), now() ),
('Sopa legumes', now(), now() ),
('Sorvete', now(), now() ),
('Sorvete Napolitano (R) Nestlé', now(), now() ),
('Suco goiaba com açúcar', now(), now() ),
('Suco laranja', now(), now() ),
('Sukiyaki', now(), now() ),
('Sumak', now(), now() ),
('Sushi', now(), now() ),
('Sushi (norimaki ou makisushi)', now(), now() ),
('Tacacá', now(), now() ),
('Tangerina', now(), now() ),
('Tapioca', now(), now() ),
('Tapioca ', now(), now() ),
('Tapioquinha com coco ', now(), now() ),
('Tapioquinha com margarina ', now(), now() ),
('Tapioquinha seca ', now(), now() ),
('Tempura', now(), now() ),
('Toddynho (R) ', now(), now() ),
('Tofu (queijo de soja)', now(), now() ),
('Tomate', now(), now() ),
('Torresmo', now(), now() ),
('Torta de cebola', now(), now() ),
('Torta de frango', now(), now() ),
('Tucumã ', now(), now() ),
('Uísque', now(), now() ),
('Urucum semente', now(), now() ),
('Uva', now(), now() ),
('Vatapá', now(), now() ),
('Vatapá paraense ', now(), now() ),
('Vinagre branco', now(), now() ),
('Vinho', now(), now() ),
('Wasabi pasta', now(), now() ),
('Wasabi pó', now(), now() ),
('Xilitos', now(), now() ),
('Yakisoba', now(), now() ),
('Yakult (R) ', now(), now() ),
('Zattar', now(), now() ),
('Zimbro', now(), now() );

INSERT INTO fontes(descricao, texto_exibicao, "createdAt", "updatedAt")
VALUES
('PINHEIRO, A. B. V.; LACERDA, E. M. A.; BENZECRY, E. H.; GOMES, M. C. S.; COSTA V. M. Tabela para avaliação do consumo Alimentar em Medidas Caseiras. 5. ed. São Paulo: Atheneu, 2004.', 'PINHEIRO et al., 2004', now(), now()),
('CARDOSO, Marly Augusto; STOCCO, Priscila Regina. Desenvolvimento de um questionário quantitativo de frequência alimentar em imigrantes japoneses e seus descendentes residentes em São Paulo, Brasil. Caderno de Saúde Pública, Rio de Janeiro, v. 16, n. 1, p. 107-114, jan. 2000.','', now(), now()),
('BOTTIN, Índia Mara; GATTI, Raquel Rosalva. Elaboração de tabela de medidas caseiras relativa à condimentos. 2011. Trabalho de Conclusão de Curso. Universidade Estadual do Centro-Oeste, Paraná.','', now(), now()),
('SABRY, M. O. D.; SAMPAIO, H. A. C.; BEZERRA, I.N. Medidas caseiras padronizadas. Em: Nádia Tavares Soares; Fernanda Maria Machado Maia. (Org.). Avaliação do consumo alimentar. 1ed. Rio de Janeiro: Medbook, 2013. cap. 3.','', now(), now()),
('GOMES, Daniela Lopes; TUMA, Rahilda Brito; DA SILVA, Elenilma Barros. Regionalização da tabela oficial de contagem de carboidratos para o tratamento de pacientes diabéticos no estado do Pará, Brasil. Cad. saúde colet., Rio de Janeiro, v. 19, n.2, 2011.','', now(), now());


INSERT INTO medidas(
            descricao, "createdAt", "updatedAt")
    VALUES ('1/2 quentinha', now(), now() ),
('à vontade', now(), now() ),
('asa G', now(), now() ),
('asa M', now(), now() ),
('asa P', now(), now() ),
('bacia média', now(), now() ),
('bacia pequena', now(), now() ),
('barra pequena', now(), now() ),
('bico de pão (bengala)', now(), now() ),
('bife grande', now(), now() ),
('bife médio', now(), now() ),
('bife pequeno', now(), now() ),
('bisnaga', now(), now() ),
('bola G', now(), now() ),
('bola média', now(), now() ),
('bola pequena', now(), now() ),
('cabeça', now(), now() ),
('cacho G', now(), now() ),
('cacho M', now(), now() ),
('cacho P', now(), now() ),
('cachoGG', now(), now() ),
('caçulinha', now(), now() ),
('calabresa/unidade', now(), now() ),
('caneca', now(), now() ),
('caneca cheia', now(), now() ),
('canudo', now(), now() ),
('coher de sopa', now(), now() ),
('colher café cheia', now(), now() ),
('colher de arroz', now(), now() ),
('colher de arroz cheia', now(), now() ),
('colher de arroz cheia desfiado', now(), now() ),
('colher de arroz cheia picada', now(), now() ),
('colher de arroz cheia picado', now(), now() ),
('colher de arroz rasa', now(), now() ),
('colher de arroz rasa ', now(), now() ),
('colher de arroz rasa desfiado', now(), now() ),
('colher de arroz rasa picada', now(), now() ),
('colher de arroz rasa picado', now(), now() ),
('colher de café', now(), now() ),
('colher de café cheia', now(), now() ),
('colher de café rasa', now(), now() ),
('colher de chá', now(), now() ),
('colher de chá cheia', now(), now() ),
('colher de chá rasa', now(), now() ),
('colher de pau média cheia', now(), now() ),
('colher de pau média rasa', now(), now() ),
('colher de pau pequena cheia', now(), now() ),
('colher de pau pequena rasa', now(), now() ),
('colher de servir', now(), now() ),
('colher de servir cheia', now(), now() ),
('colher de servir rasa', now(), now() ),
('colher de sobremesa', now(), now() ),
('colher de sobremesa cheia', now(), now() ),
('colher de sobremesa cheia em pasta', now(), now() ),
('colher de sobremesa cheia picada', now(), now() ),
('colher de sobremesa cozida', now(), now() ),
('colher de sobremesa nivelada', now(), now() ),
('colher de sobremesa rasa', now(), now() ),
('colher de sobremesa rasa em pasta', now(), now() ),
('colher de sopa', now(), now() ),
('colher de sopa ', now(), now() ),
('colher de sopa cheia', now(), now() ),
('colher de sopa cheia ', now(), now() ),
('colher de sopa cheia desfiado', now(), now() ),
('colher de sopa cheia em cubos', now(), now() ),
('colher de sopa cheia em pasta', now(), now() ),
('colher de sopa cheia em tiras', now(), now() ),
('colher de sopa cheia picada', now(), now() ),
('colher de sopa cheia picado', now(), now() ),
('colher de sopa cheia ralada', now(), now() ),
('colher de sopa nivelada', now(), now() ),
('colher de sopa picada', now(), now() ),
('colher de sopa rasa', now(), now() ),
('colher de sopa rasa desfiado', now(), now() ),
('colher de sopa rasa em pasta', now(), now() ),
('colher de sopa rasa em tiras', now(), now() ),
('colher de sopa rasa picada', now(), now() ),
('colher de sopa rasa picado', now(), now() ),
('concha', now(), now() ),
('concha cheia', now(), now() ),
('concha grande', now(), now() ),
('concha grande cheia', now(), now() ),
('concha média', now(), now() ),
('concha média ', now(), now() ),
('concha média cheia', now(), now() ),
('concha média rasa', now(), now() ),
('concha nivelada', now(), now() ),
('concha pequena', now(), now() ),
('concha pequena cheia', now(), now() ),
('concha pequena rasa', now(), now() ),
('concha rasa', now(), now() ),
('copo americano', now(), now() ),
('copo americano cheio', now(), now() ),
('copo cafezinho', now(), now() ),
('copo de requeijão', now(), now() ),
('copo descartável 200 ml', now(), now() ),
('copo descartável 300ml', now(), now() ),
('copo descartável café', now(), now() ),
('copo descartável de café', now(), now() ),
('copo descartável grande', now(), now() ),
('copo descartável pequeno', now(), now() ),
('copo duplo', now(), now() ),
('copo duplo cheio', now(), now() ),
('copo duplo nivelado', now(), now() ),
('copo P picado', now(), now() ),
('copo pequeno', now(), now() ),
('copo pequeno cheio', now(), now() ),
('copo pequeno nivelado', now(), now() ),
('coração de boi/G', now(), now() ),
('costela G', now(), now() ),
('costela M', now(), now() ),
('costela P', now(), now() ),
('coxa G', now(), now() ),
('coxa M', now(), now() ),
('coxa P', now(), now() ),
('cubo', now(), now() ),
('cuia média nivelada', now(), now() ),
('cuscuz peitinho', now(), now() ),
('dose', now(), now() ),
('escumadeira cheia', now(), now() ),
('escumadeira média cheia', now(), now() ),
('escumadeira média cheia desfiado', now(), now() ),
('escumadeira média cheia picada', now(), now() ),
('escumadeira média cheia picado', now(), now() ),
('escumadeira média rasa', now(), now() ),
('escumadeira média rasa desfiado', now(), now() ),
('escumadeira média rasa picada', now(), now() ),
('escumadeira média rasa picado', now(), now() ),
('escumadeira rasa', now(), now() ),
('espada/G', now(), now() ),
('espada/M', now(), now() ),
('espada/P', now(), now() ),
('espeto médio', now(), now() ),
('espiga G', now(), now() ),
('espiga grande', now(), now() ),
('espiga média', now(), now() ),
('espiga pequena', now(), now() ),
('fatia', now(), now() ),
('fatia fina', now(), now() ),
('fatia G', now(), now() ),
('fatia G em corte', now(), now() ),
('fatia GG', now(), now() ),
('fatia grande', now(), now() ),
('fatia grossa', now(), now() ),
('fatia M', now(), now() ),
('fatia M em corte', now(), now() ),
('fatia média', now(), now() ),
('fatia P', now(), now() ),
('fatia P em corte', now(), now() ),
('fatia pequena', now(), now() ),
('filé G', now(), now() ),
('filé M', now(), now() ),
('filé médio', now(), now() ),
('filé P', now(), now() ),
('fileira', now(), now() ),
('flor', now(), now() ),
('folha G', now(), now() ),
('folha M', now(), now() ),
('folha média', now(), now() ),
('folha P', now(), now() ),
('frango pequeno', now(), now() ),
('garfada', now(), now() ),
('garfo', now(), now() ),
('garrafa', now(), now() ),
('garrafa G', now(), now() ),
('garrafa long neck', now(), now() ),
('garrafa M', now(), now() ),
('garrafa pequena', now(), now() ),
('garrafa PET P', now(), now() ),
('gomo', now(), now() ),
('gomo M', now(), now() ),
('gomo/fatia M', now(), now() ),
('guanabara/20 cm', now(), now() ),
('guanabara/fatia', now(), now() ),
('lata', now(), now() ),
('lata grande', now(), now() ),
('lata P', now(), now() ),
('lata pequena', now(), now() ),
('médio', now(), now() ),
('no cachorro-quente', now(), now() ),
('nº15', now(), now() ),
('pacote', now(), now() ),
('pacote bolinha/palito', now(), now() ),
('pacote G', now(), now() ),
('pacote grande', now(), now() ),
('pacote individual', now(), now() ),
('pacote M', now(), now() ),
('pacote P', now(), now() ),
('pacote pequeno', now(), now() ),
('pacote porção', now(), now() ),
('pacote rosca', now(), now() ),
('pata', now(), now() ),
('pé', now(), now() ),
('peça triangular', now(), now() ),
('pedaço', now(), now() ),
('pedaço de 4 dedos (bengala)', now(), now() ),
('pedaço G', now(), now() ),
('pedaço grande', now(), now() ),
('pedaço grande de peito', now(), now() ),
('pedaço M', now(), now() ),
('pedaço médio', now(), now() ),
('pedaço médio de peito', now(), now() ),
('pedaço P', now(), now() ),
('pedaço pequeno', now(), now() ),
('pedaço pequeno de peito', now(), now() ),
('pegador', now(), now() ),
('pegador grande', now(), now() ),
('pegador médio', now(), now() ),
('pegador pequeno', now(), now() ),
('peito', now(), now() ),
('peito G', now(), now() ),
('peito M', now(), now() ),
('peito P', now(), now() ),
('pequeno', now(), now() ),
('pescoço G', now(), now() ),
('pescoço M', now(), now() ),
('pescoço médio', now(), now() ),
('pescoço P', now(), now() ),
('pires cheio picada', now(), now() ),
('pires de chá', now(), now() ),
('ponta de faca', now(), now() ),
('porção', now(), now() ),
('porção G', now(), now() ),
('porção M', now(), now() ),
('porção P', now(), now() ),
('posta G', now(), now() ),
('posta M', now(), now() ),
('posta P', now(), now() ),
('pote', now(), now() ),
('pote pequeno', now(), now() ),
('potinho', now(), now() ),
('prato', now(), now() ),
('prato de sobremesa', now(), now() ),
('prato de sobremesa cheio', now(), now() ),
('prato de sobremesa raso', now(), now() ),
('prato fundo', now(), now() ),
('prato fundo cheio', now(), now() ),
('prato fundo de caldo', now(), now() ),
('prato fundo raso', now(), now() ),
('prato raso', now(), now() ),
('prato raso cheio', now(), now() ),
('prato raso cheio picada', now(), now() ),
('prato raso raso', now(), now() ),
('prato sobremesa cheia picada', now(), now() ),
('prato sobremesa cheio', now(), now() ),
('punhado', now(), now() ),
('punhado ', now(), now() ),
('punhado bolinha', now(), now() ),
('quadrado', now(), now() ),
('ramo médio', now(), now() ),
('rodela', now(), now() ),
('rodela fina', now(), now() ),
('rodela grande', now(), now() ),
('rodela grossa', now(), now() ),
('rodela média', now(), now() ),
('rodela pequena', now(), now() ),
('sachê', now(), now() ),
('saco de dindin', now(), now() ),
('saco G', now(), now() ),
('saco grande', now(), now() ),
('saco M', now(), now() ),
('saco médio', now(), now() ),
('saco microondas', now(), now() ),
('saco P', now(), now() ),
('saco pequeno', now(), now() ),
('sacolé', now(), now() ),
('sobrecoxa G', now(), now() ),
('sobrecoxa M', now(), now() ),
('sobrecoxa P', now(), now() ),
('taça', now(), now() ),
('taça cheia', now(), now() ),
('taça de sobremesa cheia', now(), now() ),
('taça de sobremesa rasa', now(), now() ),
('taça média', now(), now() ),
('taça rasa', now(), now() ),
('tempero', now(), now() ),
('tigela', now(), now() ),
('tigela pequena', now(), now() ),
('tigela pequena cheia', now(), now() ),
('tira', now(), now() ),
('tradicional', now(), now() ),
('trufa', now(), now() ),
('tulipa', now(), now() ),
('unidade', now(), now() ),
('unidade (apenas carne)', now(), now() ),
('unidade (carioquinha)', now(), now() ),
('unidade baby P', now(), now() ),
('unidade bolinha', now(), now() ),
('unidade com osso', now(), now() ),
('unidade comercial', now(), now() ),
('unidade fina', now(), now() ),
('unidade G', now(), now() ),
('unidade G sem casca', now(), now() ),
('unidade grande', now(), now() ),
('unidade individual pequena', now(), now() ),
('unidade M', now(), now() ),
('unidade M (passarinho)', now(), now() ),
('unidade M sem casca', now(), now() ),
('unidade média', now(), now() ),
('unidade média coité', now(), now() ),
('unidade média em conserva', now(), now() ),
('unidade mini', now(), now() ),
('unidade P', now(), now() ),
('unidade P (1 ovo)', now(), now() ),
('unidade P sem casca', now(), now() ),
('unidade pequena', now(), now() ),
('unidade pequena espada', now(), now() ),
('unidade pequena itamaracá', now(), now() ),
('unidade rosca', now(), now() ),
('unidade sem miolo', now(), now() ),
('unidade sem miolo (carioquinha)', now(), now() ),
('unidaide', now(), now() ),
('xícara de café', now(), now() ),
('xícara de café cheia', now(), now() ),
('xícara de chá', now(), now() ),
('xícara de chá cheia', now(), now() ),
('xícara de chá rasa', now(), now() ),
('xícara Duralex', now(), now() );
